FROM itzg/minecraft-server:latest

ENV EULA=TRUE
ENV TYPE=PAPER
ENV VERSION=1.16.5
ENV GAMEMODE=survival
ENV DIFFICULTY=normal
ENV MAX_PLAYERS=20
ENV SERVER_NAME=UZ-Minecraft-Server
ENV LEVEL=BedrockWorld
ENV VIEW_DISTANCE=8
ENV ONLINE_MODE=FALSE

EXPOSE 25565
