version: '3.8'

services:
  minecraft:
    build: .
    container_name: bedrock-minecraft
    restart: unless-stopped
    
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    
    volumes:
      # Dunyo saqlash (o'chirmasa ham qoladi)
      - ./worlds:/server/worlds
      - ./server.properties:/server/server.properties
      - ./allowlist.json:/server/allowlist.json
      - ./permissions.json:/server/permissions.json
    
    environment:
      - EULA=TRUE
    
    # Oracle 1GB RAM uchun
    mem_limit: 768m
    mem_reservation: 512m
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
