FROM itzg/minecraft-server:java16

ENV EULA=TRUE
ENV TYPE=PAPER
ENV VERSION=1.16.5
ENV GAMEMODE=survival
ENV DIFFICULTY=normal
ENV MAX_PLAYERS=5
ENV SERVER_NAME=UZ-Minecraft-Server
ENV LEVEL=BedrockWorld
ENV VIEW_DISTANCE=4
ENV ONLINE_MODE=FALSE
ENV INIT_MEMORY=256M
ENV MAX_MEMORY=400M

EXPOSE 25565
