# ═══════════════════════════════════════
#   BEDROCK SERVER - ASOSIY SOZLAMALAR
# ═══════════════════════════════════════

server-name=UZ Minecraft Server
gamemode=survival
difficulty=normal
allow-cheats=false
max-players=20

# Dunyo
level-name=BedrockWorld
level-seed=
level-type=DEFAULT
default-player-permission-level=member

# Tarmoq
server-port=19132
server-portv6=19133
online-mode=true

# Ishlash tezligi (Oracle 1GB RAM uchun optimallashtirilgan)
view-distance=8
tick-distance=4
max-threads=2
compression-threshold=1

# Xavfsizlik
white-list=false
texturepack-required=false
content-log-file-enabled=false

# O'yin sozlamalari
pvp=true
natural-regeneration=true
respawn-radius=0
enable-lan-visibility=true
player-movement-score-threshold=20
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
correct-player-movement=false
server-authoritative-movement=server-auth
server-authoritative-block-breaking=false
